# Generated by Django 4.0.4 on 2023-09-25 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.PositiveIntegerField()),
                ('Month', models.PositiveSmallIntegerField()),
                ('Quarter', models.PositiveSmallIntegerField()),
                ('Country', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Function', models.CharField(max_length=30)),
                ('Description', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=30)),
                ('Severity', models.CharField(max_length=30)),
                ('Unit', models.CharField(max_length=30)),
                ('Quantity', models.IntegerField()),
                ('Verified', models.BooleanField(default=False)),
                ('Remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('Evidence1', models.FileField(blank=True, null=True, upload_to='ESG/Evidences/')),
                ('Evidence2', models.FileField(blank=True, null=True, upload_to='ESG/Evidences/')),
                ('Evidence3', models.FileField(blank=True, null=True, upload_to='ESG/Evidences/')),
                ('Evidence4', models.FileField(blank=True, null=True, upload_to='ESG/Evidences/')),
                ('Created_On', models.DateTimeField(auto_now_add=True)),
                ('Updated_On', models.DateTimeField(auto_now=True)),
                ('Entered_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_entered_by', to=settings.AUTH_USER_MODEL)),
                ('Verified_By', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
