# Generated by Django 4.0.4 on 2023-09-25 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports01', '0002_esg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='esg',
            old_name='Evidence1',
            new_name='ESG_Evidence1',
        ),
        migrations.RenameField(
            model_name='esg',
            old_name='Evidence2',
            new_name='ESG_Evidence2',
        ),
        migrations.RenameField(
            model_name='esg',
            old_name='Evidence3',
            new_name='ESG_Evidence3',
        ),
        migrations.RenameField(
            model_name='esg',
            old_name='Evidence4',
            new_name='ESG_Evidence4',
        ),
        migrations.RemoveField(
            model_name='esg',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='esg',
            name='Updated_By',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='esg_updated_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='esg',
            name='Description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='esg',
            name='Entered_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esg_entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='esg',
            name='Verified_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='esg_verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
