# Generated by Django 4.0.4 on 2023-09-25 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reports01', '0003_rename_evidence1_esg_esg_evidence1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disposalsummary',
            name='Entered_By',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='disposalsummary',
            name='Verified_By',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
