# Generated by Django 4.0.4 on 2023-09-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0004_alter_disposalsummary_entered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esg',
            name='ESG_Evidence1',
            field=models.FileField(blank=True, null=True, upload_to='ESG_Evidences/'),
        ),
        migrations.AlterField(
            model_name='esg',
            name='ESG_Evidence2',
            field=models.FileField(blank=True, null=True, upload_to='ESG_Evidences/'),
        ),
        migrations.AlterField(
            model_name='esg',
            name='ESG_Evidence3',
            field=models.FileField(blank=True, null=True, upload_to='ESG_Evidences/'),
        ),
        migrations.AlterField(
            model_name='esg',
            name='ESG_Evidence4',
            field=models.FileField(blank=True, null=True, upload_to='ESG_Evidences/'),
        ),
    ]
