# Generated by Django 4.0.4 on 2023-09-26 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0006_alter_esg_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='e_waste_disposal',
            name='Comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='non_routine_disposal',
            name='Comments',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
