# Generated by Django 4.0.4 on 2023-09-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0007_e_waste_disposal_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_waste_disposal',
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='non_routine_disposal',
            name='Comments',
        ),
        migrations.AddField(
            model_name='e_waste_disposal',
            name='Type',
            field=models.CharField(default='E-Waste Disposal/ Scrap Activity', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='non_routine_disposal',
            name='Type',
            field=models.CharField(default='Non-Routine Waste Disposal/ Scrap Activity', max_length=100),
            preserve_default=False,
        ),
    ]
