# Generated by Django 4.0.4 on 2023-09-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0008_remove_e_waste_disposal_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalsummary',
            name='Items',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
