# Generated by Django 4.0.4 on 2023-09-27 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0009_disposalsummary_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disposalsummary',
            name='Items',
        ),
    ]
