# Generated by Django 4.0.4 on 2023-09-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0010_remove_disposalsummary_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalsummary',
            name='Items',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
