# Generated by Django 4.0.4 on 2023-09-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0012_remove_disposalsummary_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esg',
            name='Quantity',
            field=models.FloatField(),
        ),
    ]
