# Generated by Django 4.0.4 on 2023-09-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0013_alter_esg_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='disposalsummary',
            name='Items',
            field=models.IntegerField(default=0),
        ),
    ]
