# Generated by Django 4.0.4 on 2023-09-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0014_disposalsummary_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disposalsummary',
            old_name='Items',
            new_name='Count',
        ),
        migrations.AlterUniqueTogether(
            name='disposalsummary',
            unique_together={('Date', 'Location', 'Type')},
        ),
    ]
