# Generated by Django 4.0.4 on 2023-09-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0015_rename_items_disposalsummary_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acknowledgement',
            name='course_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='acknowledgement',
            name='course_quarter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='planned_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trainingcalendar',
            name='planned_quarter',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='course_month',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='course_quarter',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
