# Generated by Django 4.0.4 on 2023-09-30 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0016_alter_acknowledgement_course_month_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Country',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Entity',
            new_name='Entity',
        ),
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Location',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Month',
            new_name='Month',
        ),
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Quarter',
            new_name='Quarter',
        ),
        migrations.RenameField(
            model_name='opex_data',
            old_name='OPEX_Year',
            new_name='Year',
        ),
        migrations.AlterField(
            model_name='opex_data',
            name='GL',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data', to='Reports01.expense_heads'),
        ),
    ]
