# Generated by Django 4.0.4 on 2023-10-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0017_rename_opex_country_opex_data_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='change_desc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
