# Generated by Django 4.0.4 on 2026-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reports01', '0018_course_change_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident_data',
            name='Status',
            field=models.CharField(max_length=20),
        ),
    ]
